<?php

namespace Database\Seeders;

use App\Models\Itm1;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Itm1Seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Itm1::insert([
            [
                'Itemcode' => 'ITM1-001',
                'Itemname' => 'Banana Snack - Kripik Pisang Kepok (Rasa Jagung Manis)',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Banana Snack ',
                'MP_ProductCategory' => 'Makanan',
                'Etalase' => 'Fruit Chips',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Kripik pisang kepok dengan rasa jagung manis',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' => 0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 200,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/banana-snack/banana_snack_jagung_manis_01.jpg",
                'MP_Pic2' => 'asset("img/banana-snack/banana_snack_jagung_manis_01.jpg")',
                'MP_Pic3' => 'img/banana-snack/banana_snack_jagung_manis_02.jpg',
                'MP_Pic4' => 'asset("img/banana-snack/banana_snack_jagung_manis_01.jpg")',
                'MP_Pic5' => 'asset("img/banana-snack/banana_snack_jagung_manis_02.jpg")',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackJagungManis',
                'MPProductLink' => '',
            ],
            [
                'Itemcode' => 'ITM1-002',
                'Itemname' => 'Banana Snack - Kripik Pisang Kepok (Rasa Pedas Manis)',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Banana Snack ',
                'MP_ProductCategory' => 'Makanan',
                'Etalase' => 'Fruit Chips',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Kripik pisang kepok dengan rasa pedas manis',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' =>0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 150,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/banana-snack/banana_snack_pedas_manis_02.jpg",
                'MP_Pic2' => 'img/banana-snack/banana_snack_pedas_manis_01.jpg',
                'MP_Pic3' => 'img/banana-snack/banana_snack_pedas_manis_02.jpg',
                'MP_Pic4' => 'img/banana-snack/banana_snack_pedas_manis_01.jpg',
                'MP_Pic5' => 'img/banana-snack/banana_snack_pedas_manis_02.jpg',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackPedasManis',
                'MPProductLink' => '',
            ],
            [
                'Itemcode' => 'ITM1-003',
                'Itemname' => 'Rengginang Buah Naga - Dragon Reco',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Dragon Rengginang ',
                'MP_ProductCategory' => 'Makanan',
                'Etalase' => 'Fruit Chips',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Dragon Rengginang / Rengginang Buah Naga Dengan Rasa Coklat',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' =>0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 160,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/rengginang/dragon_reco.jpg",
                'MP_Pic2' => 'img/rengginang/rengginang_all.jpg',
                'MP_Pic3' => 'img/rengginang/dragon_reco.jpg',
                'MP_Pic4' => 'img/rengginang/rengginang_all.jpg',
                'MP_Pic5' => 'img/rengginang/dragon_reco.jpg',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackPedasManis',
                'MPProductLink' => '',
            ],
            [
                'Itemcode' => 'ITM1-004',
                'Itemname' => 'Rengginang Buah Naga - Salted Egg',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Dragon Rengginang ',
                'MP_ProductCategory' => 'Makanan',
                'Etalase' => 'Fruit Chips',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Dragon Rengginang / Rengginang Buah Naga Dengan Rasa Telur Asin',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' =>0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 160,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/rengginang/rengginang_salted_egg_01.jpg",
                'MP_Pic2' => 'img/rengginang/rengginang_all.jpg',
                'MP_Pic3' => 'img/rengginang/rengginang_salted_egg_01.jpg',
                'MP_Pic4' => 'img/rengginang/rengginang_all.jpg',
                'MP_Pic5' => 'img/rengginang/rengginang_salted_egg_01.jpg',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackPedasManis',
                'MPProductLink' => '',
            ],
            [
                'Itemcode' => 'ITM1-005',
                'Itemname' => 'Dragon Drink - Varian Original',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Dragon Drink ',
                'MP_ProductCategory' => 'Minuman',
                'Etalase' => 'Dragon Drink',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Dragon Drink, Minuman dengan rasa exstra buah naga yang segar dengan rasa original',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' =>0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 150,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/dragon_drink/dragon_drink_original.jpg",
                'MP_Pic2' => 'img/dragon_drink/dragon_drink_all.jpg',
                'MP_Pic3' => 'img/dragon_drink/dragon_drink_original.jpg',
                'MP_Pic4' => 'img/dragon_drink/dragon_drink_all.jpg',
                'MP_Pic5' => 'img/dragon_drink/dragon_drink_original.jpg',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackPedasManis',
                'MPProductLink' => '',
            ],
            [
                'Itemcode' => 'ITM1-006',
                'Itemname' => 'Dragon Drink - Spesial Varian Jahe',
                'MPName' => 'Shoope',
                'MP_ProductName' => 'Dragon Drink ',
                'MP_ProductCategory' => 'Minuman',
                'Etalase' => 'Dragon Drink',
                'MPKondisi' => 'Baru',
                'MP_ProductDescription' => 'Dragon Drink, Minuman dengan rasa exstra buah naga yang segar dengan rasa spesial jahe',
                'UrlVideoProduct' => '',
                'MP_MinOrder' => 1,
                'MP_UnitPrice' => 50000,
                'MP_GroceryPrice' =>0,
                'MPStatusProduct' => true,
                'MPStockProduct' => 150,
                'MPSKU' => '',
                'MPProductWeight' => 500,
                'MP_ProductLength' => 0,
                'MP_ProductWidth' => 0,
                'MP_ProductHeight' => 0,
                'MP_ProdInsurance' => false,
                'MP_Delivery' => '',
                'MP_POProduct' => true,
                'MP_Pic1' => "img/dragon_drink/dragon_drink_jahe.jpg",
                'MP_Pic2' => 'img/dragon_drink/dragon_drink_all.jpg',
                'MP_Pic3' => 'img/dragon_drink/dragon_drink_jahe.jpg',
                'MP_Pic4' => 'img/dragon_drink/dragon_drink_all.jpg',
                'MP_Pic5' => 'img/dragon_drink/dragon_drink_jahe.jpg',
                'PromoSupport' => '#Snack #BananaSnack #BananaSnackPedasManis',
                'MPProductLink' => '',
            ],
        ]);
    }
}
